"""empty message

Revision ID: 561ba9f5cd01
Revises: a823804f755f
Create Date: 2024-07-08 21:57:30.779596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561ba9f5cd01'
down_revision = 'a823804f755f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
