"""empty message

Revision ID: f3c189e1848e
Revises: 9e0a1b4d9055
Create Date: 2024-07-10 11:50:48.515014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3c189e1848e'
down_revision = '9e0a1b4d9055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('notifications_ibfk_1', type_='foreignkey')
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('notifications_ibfk_1', 'users', ['recipient_id'], ['user_id'])

    # ### end Alembic commands ###
